"""Add doi and citation_count to sources

Revision ID: 26f5535a89b8
Revises: b60e6fe33dde
Create Date: 2025-07-11 17:31:57.089840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26f5535a89b8'
down_revision: Union[str, Sequence[str], None] = 'b60e6fe33dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('doi', sa.String(), nullable=True))
    op.add_column('sources', sa.Column('citation_count', sa.Integer(), nullable=True))
    op.add_column('sources', sa.Column('full_content', sa.Text(), nullable=True))
    op.add_column('sources', sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_index('ix_sources_doi', 'sources', ['doi'])
    op.create_index('ix_sources_citation_count', 'sources', ['citation_count'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sources_citation_count', 'sources')
    op.drop_index('ix_sources_doi', 'sources')
    op.drop_column('sources', 'scraped_at')
    op.drop_column('sources', 'full_content')
    op.drop_column('sources', 'citation_count')
    op.drop_column('sources', 'doi')
    # ### end Alembic commands ###
