"""Add doi and citation_count to sources

Revision ID: 6b1e2e689832
Revises: 26f5535a89b8
Create Date: 2025-07-12 11:45:20.242082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1e2e689832'
down_revision: Union[str, Sequence[str], None] = '26f5535a89b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('doi', sa.String(), nullable=True))
    op.add_column('sources', sa.Column('citation_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sources_citation_count'), 'sources', ['citation_count'], unique=False)
    op.create_index(op.f('ix_sources_doi'), 'sources', ['doi'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_doi'), table_name='sources')
    op.drop_index(op.f('ix_sources_citation_count'), table_name='sources')
    op.drop_column('sources', 'citation_count')
    op.drop_column('sources', 'doi')
    # ### end Alembic commands ###
